# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: omniscient.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'omniscient.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10omniscient.proto\x12\nomniscient\"(\n\x07Payment\x12\r\n\x05store\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\"\"\n\x0fPaymentResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"2\n\tDateQuery\x12\x12\n\nstart_date\x18\x01 \x01(\t\x12\x11\n\tstop_date\x18\x02 \x01(\t\"0\n\rQueryResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\x32L\n\nAddPayment\x12>\n\nAddPayment\x12\x13.omniscient.Payment\x1a\x1b.omniscient.PaymentResponse2B\n\x05Query\x12\x39\n\x05Query\x12\x15.omniscient.DateQuery\x1a\x19.omniscient.QueryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'omniscient_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PAYMENT']._serialized_start=32
  _globals['_PAYMENT']._serialized_end=72
  _globals['_PAYMENTRESPONSE']._serialized_start=74
  _globals['_PAYMENTRESPONSE']._serialized_end=108
  _globals['_DATEQUERY']._serialized_start=110
  _globals['_DATEQUERY']._serialized_end=160
  _globals['_QUERYRESPONSE']._serialized_start=162
  _globals['_QUERYRESPONSE']._serialized_end=210
  _globals['_ADDPAYMENT']._serialized_start=212
  _globals['_ADDPAYMENT']._serialized_end=288
  _globals['_QUERY']._serialized_start=290
  _globals['_QUERY']._serialized_end=356
# @@protoc_insertion_point(module_scope)
